sudo: required
dist: trusty
addons:
  mariadb: '10.2'
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
services:
- mysql
language: node_js
node_js:
- stable
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- cd src/front-src
- mysql -e 'create database pgp_test;'
- mysql -u root pgp_test < ../initdb_test/init_test.sql
install:
- npm install --prefix ./src/front-src/
- npm install --prefix ./src/back-src/
- src/front-src/node_modules/protractor/bin/webdriver-manager update
script:
- npm start --prefix ../back-src/ &
- ng e2e
env:
- NODE_ENV=TEST NODE_PORT=3000 DB_SERVER_PORT=3306 MYSQL_TYPE=mysql MYSQL_HOST=localhost
  MYSQL_DATABASE=pgp_test MYSQL_USER=root MYSQL_PASSWORD=
mysql:
  adapter: mysql2
  username: root
  encoding: utf8
  database: pgp_test
before_deploy:
  - cd ../
  - zip -r release.zip back-src/ front-src/ -x "back-src/node_modules/*" "front-src/node_modules/*"
deploy:
  provider: releases
  api_key:
    secure: nGgCblb0PD3e6ZYh2BhuELHHzX0w+Q9Tgkyrj5tjRhDvP7IhgHQ9aHb8tZSE4UlQQRGSU0H8BOSm2n5DkRGkavlczaL3yNGxjG4Wg6e5DC0/T0bYhJ7muDpmNnn+uvS6mtI1bu5+IB0EyfFqsPYpfWTMPBjM98+lv7HgQLg5U5fZwdIrZzLiEZJpcrcDUstWD14F39HktLWpSZv7BrkEZ2YhT3IfNruQz4N7iZRF2/lat2P3SOKkI5D0jrZr8181Q1T1nSq0sOk6/x66rpQ73XKhXf5TqmahNf7AAgMxMgmai3saDwEzWyOjHB36GTjyHkxfF8PnPt2o8ABVin1Syu9VS/U8I2rPXYCrx1bdVkhPc9ivrklcp7AYhen3pzEehkHxvQdbgUpHwUZGgL1IR3CwergcOF/VRDh8ekIObe0uKqHeZcLKg5t/6a7HTjfn7trF8OxgqnDP58pF144EVvmZ3O9BSH40vCf9Bj7BO0gEtE2QRAn79FnY7PqTJaptDGe+SgfAYWH2Q8OQpZqLxE+hhm4rmB1GICchYvwKU3MqNOwjoDWJ77kl69DiuycHE7zmmpin5RQOxWe8pHrbNp8m5XuOr45HE7E7bGBvfqCf6B2sLnxSSED1Td00KvuxtKauQNN0V/w+d3PmDwaRlMe6c/okz97lmnJ/uR7wuW4=
  file: release.zip
  skip_cleanup: true
  on:
    tags: true
    repo: Lunya/PGP_2017
