sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
services:
  - mysql
language: node_js
node_js:
  - "stable"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install --prefix ./src/front-src/
  - npm install --prefix ./src/back-src/
  - src/front-src/node_modules/protractor/bin/webdriver-manager update
script:
  - npm start &
  - ng e2e
