version: "2.3"

services:
  mariadb: # by default, expose 3306 port
    image: mariadb:10.2
    restart: always
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      #MYSQL_USER: karom
      #MYSQL_PASSWORD: root
      MYSQL_DATABASE: pgp
    ports:
      - "3316:3306"
  server:
    build:
      context: .
      dockerfile: Dockerfile_prod
    image: pgp:prod
    volumes:
      - ./back-src:/home/node/app
      - ./front-src:/home/node/front
    environment:
      - NODE_ENV=production
      - NODE_PORT=4200
      - DB_SERVER_HOST=mariadb
      - DB_SERVER_PORT=3306
      - DB_SERVER_USER=root
      - DB_SERVER_PASSWORD=root
      - DB_NAME=pgp
    ports:
      - "4200:4200"
    depends_on:
      - mariadb
    init: true
